knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20 # In seconds
    pdf:
        enabled:    true
        #binary:     '%env(WKHTMLTOPDF_PATH)%'
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:    []
    image:
        enabled:    true
        binary:     '%kernel.project_dir%/vendor/bin/wkhtmltoimage-amd64'
        options:    []
